/*
 * This file is generated by jOOQ.
 */
package raubach.fricklweb.server.database.tables.records;


import org.jooq.*;
import org.jooq.impl.*;

import java.sql.*;

import javax.annotation.*;

import raubach.fricklweb.server.database.tables.*;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.11.9"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AlbumsRecord extends UpdatableRecordImpl<AlbumsRecord> implements Record7<Integer, String, String, Integer, Integer, Timestamp, Timestamp>
{

	private static final long serialVersionUID = 829462976;

	/**
	 * Create a detached AlbumsRecord
	 */
	public AlbumsRecord()
	{
		super(Albums.ALBUMS);
	}

	/**
	 * Create a detached, initialised AlbumsRecord
	 */
	public AlbumsRecord(Integer id, String name, String description, Integer bannerImageId, Integer parentAlbumId, Timestamp createdOn, Timestamp updatedOn)
	{
		super(Albums.ALBUMS);

		set(0, id);
		set(1, name);
		set(2, description);
		set(3, bannerImageId);
		set(4, parentAlbumId);
		set(5, createdOn);
		set(6, updatedOn);
	}

	/**
	 * Getter for <code>frickl.albums.id</code>.
	 */
	public Integer getId()
	{
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>frickl.albums.id</code>.
	 */
	public void setId(Integer value)
	{
		set(0, value);
	}

	/**
	 * Getter for <code>frickl.albums.name</code>.
	 */
	public String getName()
	{
		return (String) get(1);
	}

	/**
	 * Setter for <code>frickl.albums.name</code>.
	 */
	public void setName(String value)
	{
		set(1, value);
	}

	/**
	 * Getter for <code>frickl.albums.description</code>.
	 */
	public String getDescription()
	{
		return (String) get(2);
	}

	/**
	 * Setter for <code>frickl.albums.description</code>.
	 */
	public void setDescription(String value)
	{
		set(2, value);
	}

	/**
	 * Getter for <code>frickl.albums.banner_image_id</code>.
	 */
	public Integer getBannerImageId()
	{
		return (Integer) get(3);
	}

	/**
	 * Setter for <code>frickl.albums.banner_image_id</code>.
	 */
	public void setBannerImageId(Integer value)
	{
		set(3, value);
	}

	/**
	 * Getter for <code>frickl.albums.parent_album_id</code>.
	 */
	public Integer getParentAlbumId()
	{
		return (Integer) get(4);
	}

	/**
	 * Setter for <code>frickl.albums.parent_album_id</code>.
	 */
	public void setParentAlbumId(Integer value)
	{
		set(4, value);
	}

	/**
	 * Getter for <code>frickl.albums.created_on</code>.
	 */
	public Timestamp getCreatedOn()
	{
		return (Timestamp) get(5);
	}

	/**
	 * Setter for <code>frickl.albums.created_on</code>.
	 */
	public void setCreatedOn(Timestamp value)
	{
		set(5, value);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>frickl.albums.updated_on</code>.
	 */
	public Timestamp getUpdatedOn()
	{
		return (Timestamp) get(6);
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>frickl.albums.updated_on</code>.
	 */
	public void setUpdatedOn(Timestamp value)
	{
		set(6, value);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key()
	{
		return (Record1) super.key();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, String, String, Integer, Integer, Timestamp, Timestamp> fieldsRow()
	{
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, String, String, Integer, Integer, Timestamp, Timestamp> valuesRow()
	{
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1()
	{
		return Albums.ALBUMS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2()
	{
		return Albums.ALBUMS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3()
	{
		return Albums.ALBUMS.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4()
	{
		return Albums.ALBUMS.BANNER_IMAGE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5()
	{
		return Albums.ALBUMS.PARENT_ALBUM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6()
	{
		return Albums.ALBUMS.CREATED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7()
	{
		return Albums.ALBUMS.UPDATED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer component1()
	{
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String component2()
	{
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String component3()
	{
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer component4()
	{
		return getBannerImageId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer component5()
	{
		return getParentAlbumId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp component6()
	{
		return getCreatedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp component7()
	{
		return getUpdatedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1()
	{
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2()
	{
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3()
	{
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4()
	{
		return getBannerImageId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5()
	{
		return getParentAlbumId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6()
	{
		return getCreatedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7()
	{
		return getUpdatedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlbumsRecord value1(Integer value)
	{
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlbumsRecord value2(String value)
	{
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlbumsRecord value3(String value)
	{
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlbumsRecord value4(Integer value)
	{
		setBannerImageId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlbumsRecord value5(Integer value)
	{
		setParentAlbumId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlbumsRecord value6(Timestamp value)
	{
		setCreatedOn(value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlbumsRecord value7(Timestamp value)
	{
		setUpdatedOn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AlbumsRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, Timestamp value6, Timestamp value7)
	{
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}
}
