/*
 * This file is generated by jOOQ.
 */
package raubach.fricklweb.server.database.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import raubach.fricklweb.server.database.tables.ImageTags;

import javax.annotation.Generated;


/**
 * This table joins `images` and `tags` and therefore defines which tags an
 * image is tagged with.
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.11.9"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ImageTagsRecord extends UpdatableRecordImpl<ImageTagsRecord> implements Record2<Integer, Integer>
{

	private static final long serialVersionUID = -37226723;

	/**
	 * Create a detached ImageTagsRecord
	 */
	public ImageTagsRecord()
	{
		super(ImageTags.IMAGE_TAGS);
	}

	/**
	 * Create a detached, initialised ImageTagsRecord
	 */
	public ImageTagsRecord(Integer imageId, Integer tagId)
	{
		super(ImageTags.IMAGE_TAGS);

		set(0, imageId);
		set(1, tagId);
	}

	/**
	 * Getter for <code>frickl.image_tags.image_id</code>. The foreign key id of the referenced image.
	 */
	public Integer getImageId()
	{
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>frickl.image_tags.image_id</code>. The foreign key id of the referenced image.
	 */
	public void setImageId(Integer value)
	{
		set(0, value);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>frickl.image_tags.tag_id</code>. The foreign key id of the referenced tag.
	 */
	public Integer getTagId()
	{
		return (Integer) get(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>frickl.image_tags.tag_id</code>. The foreign key id of the referenced tag.
	 */
	public void setTagId(Integer value)
	{
		set(1, value);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Integer, Integer> key()
	{
		return (Record2) super.key();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> fieldsRow()
	{
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> valuesRow()
	{
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1()
	{
		return ImageTags.IMAGE_TAGS.IMAGE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2()
	{
		return ImageTags.IMAGE_TAGS.TAG_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer component1()
	{
		return getImageId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer component2()
	{
		return getTagId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1()
	{
		return getImageId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2()
	{
		return getTagId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImageTagsRecord value1(Integer value)
	{
		setImageId(value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImageTagsRecord value2(Integer value)
	{
		setTagId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ImageTagsRecord values(Integer value1, Integer value2)
	{
		value1(value1);
		value2(value2);
		return this;
	}
}
