/*
 * This file is generated by jOOQ.
 */
package raubach.fricklweb.server.database.tables.records;


import org.jooq.*;
import org.jooq.impl.*;

import java.sql.*;

import javax.annotation.*;

import raubach.fricklweb.server.database.tables.*;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.11.9"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TagsRecord extends UpdatableRecordImpl<TagsRecord> implements Record4<Integer, String, Timestamp, Timestamp>
{

	private static final long serialVersionUID = 115441923;

	/**
	 * Create a detached TagsRecord
	 */
	public TagsRecord()
	{
		super(Tags.TAGS);
	}

	/**
	 * Create a detached, initialised TagsRecord
	 */
	public TagsRecord(Integer id, String name, Timestamp createdOn, Timestamp updatedOn)
	{
		super(Tags.TAGS);

		set(0, id);
		set(1, name);
		set(2, createdOn);
		set(3, updatedOn);
	}

	/**
	 * Getter for <code>frickl.tags.id</code>.
	 */
	public Integer getId()
	{
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>frickl.tags.id</code>.
	 */
	public void setId(Integer value)
	{
		set(0, value);
	}

	/**
	 * Getter for <code>frickl.tags.name</code>.
	 */
	public String getName()
	{
		return (String) get(1);
	}

	/**
	 * Setter for <code>frickl.tags.name</code>.
	 */
	public void setName(String value)
	{
		set(1, value);
	}

	/**
	 * Getter for <code>frickl.tags.created_on</code>.
	 */
	public Timestamp getCreatedOn()
	{
		return (Timestamp) get(2);
	}

	/**
	 * Setter for <code>frickl.tags.created_on</code>.
	 */
	public void setCreatedOn(Timestamp value)
	{
		set(2, value);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>frickl.tags.updated_on</code>.
	 */
	public Timestamp getUpdatedOn()
	{
		return (Timestamp) get(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>frickl.tags.updated_on</code>.
	 */
	public void setUpdatedOn(Timestamp value)
	{
		set(3, value);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key()
	{
		return (Record1) super.key();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, String, Timestamp, Timestamp> fieldsRow()
	{
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, String, Timestamp, Timestamp> valuesRow()
	{
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1()
	{
		return Tags.TAGS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2()
	{
		return Tags.TAGS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3()
	{
		return Tags.TAGS.CREATED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4()
	{
		return Tags.TAGS.UPDATED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer component1()
	{
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String component2()
	{
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp component3()
	{
		return getCreatedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp component4()
	{
		return getUpdatedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1()
	{
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2()
	{
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3()
	{
		return getCreatedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4()
	{
		return getUpdatedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagsRecord value1(Integer value)
	{
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagsRecord value2(String value)
	{
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagsRecord value3(Timestamp value)
	{
		setCreatedOn(value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagsRecord value4(Timestamp value)
	{
		setUpdatedOn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagsRecord values(Integer value1, String value2, Timestamp value3, Timestamp value4)
	{
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}
}
