/*
 * This file is generated by jOOQ.
 */
package raubach.fricklweb.server.database.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlbumCounts implements Serializable {

    private static final long serialVersionUID = -1952715907;

    private Integer   albumId;
    private Integer   imageCount;
    private Integer   imageCountPublic;
    private Integer   albumCount;
    private Integer   imageViewCount;
    private Timestamp newestImage;
    private Timestamp oldestImage;

    public AlbumCounts() {}

    public AlbumCounts(AlbumCounts value) {
        this.albumId = value.albumId;
        this.imageCount = value.imageCount;
        this.imageCountPublic = value.imageCountPublic;
        this.albumCount = value.albumCount;
        this.imageViewCount = value.imageViewCount;
        this.newestImage = value.newestImage;
        this.oldestImage = value.oldestImage;
    }

    public AlbumCounts(
        Integer   albumId,
        Integer   imageCount,
        Integer   imageCountPublic,
        Integer   albumCount,
        Integer   imageViewCount,
        Timestamp newestImage,
        Timestamp oldestImage
    ) {
        this.albumId = albumId;
        this.imageCount = imageCount;
        this.imageCountPublic = imageCountPublic;
        this.albumCount = albumCount;
        this.imageViewCount = imageViewCount;
        this.newestImage = newestImage;
        this.oldestImage = oldestImage;
    }

    public Integer getAlbumId() {
        return this.albumId;
    }

    public void setAlbumId(Integer albumId) {
        this.albumId = albumId;
    }

    public Integer getImageCount() {
        return this.imageCount;
    }

    public void setImageCount(Integer imageCount) {
        this.imageCount = imageCount;
    }

    public Integer getImageCountPublic() {
        return this.imageCountPublic;
    }

    public void setImageCountPublic(Integer imageCountPublic) {
        this.imageCountPublic = imageCountPublic;
    }

    public Integer getAlbumCount() {
        return this.albumCount;
    }

    public void setAlbumCount(Integer albumCount) {
        this.albumCount = albumCount;
    }

    public Integer getImageViewCount() {
        return this.imageViewCount;
    }

    public void setImageViewCount(Integer imageViewCount) {
        this.imageViewCount = imageViewCount;
    }

    public Timestamp getNewestImage() {
        return this.newestImage;
    }

    public void setNewestImage(Timestamp newestImage) {
        this.newestImage = newestImage;
    }

    public Timestamp getOldestImage() {
        return this.oldestImage;
    }

    public void setOldestImage(Timestamp oldestImage) {
        this.oldestImage = oldestImage;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AlbumCounts (");

        sb.append(albumId);
        sb.append(", ").append(imageCount);
        sb.append(", ").append(imageCountPublic);
        sb.append(", ").append(albumCount);
        sb.append(", ").append(imageViewCount);
        sb.append(", ").append(newestImage);
        sb.append(", ").append(oldestImage);

        sb.append(")");
        return sb.toString();
    }
}
