/*
 * This file is generated by jOOQ.
 */
package raubach.fricklweb.server.database.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This table contains the mapping between access tokens and albums.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlbumTokens implements Serializable {

    private static final long serialVersionUID = 1769665801;

    private Integer   albumId;
    private Integer   accessTokenId;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public AlbumTokens() {}

    public AlbumTokens(AlbumTokens value) {
        this.albumId = value.albumId;
        this.accessTokenId = value.accessTokenId;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public AlbumTokens(
        Integer   albumId,
        Integer   accessTokenId,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.albumId = albumId;
        this.accessTokenId = accessTokenId;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    public Integer getAlbumId() {
        return this.albumId;
    }

    public void setAlbumId(Integer albumId) {
        this.albumId = albumId;
    }

    public Integer getAccessTokenId() {
        return this.accessTokenId;
    }

    public void setAccessTokenId(Integer accessTokenId) {
        this.accessTokenId = accessTokenId;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AlbumTokens (");

        sb.append(albumId);
        sb.append(", ").append(accessTokenId);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
