/*
 * This file is generated by jOOQ.
 */
package raubach.fricklweb.server.database.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlbumAccessToken implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   albumId;
    private String    albumName;
    private String    albumDescription;
    private Integer   tokenId;
    private String    tokenToken;
    private Timestamp tokenExpiresOn;

    public AlbumAccessToken() {}

    public AlbumAccessToken(AlbumAccessToken value) {
        this.albumId = value.albumId;
        this.albumName = value.albumName;
        this.albumDescription = value.albumDescription;
        this.tokenId = value.tokenId;
        this.tokenToken = value.tokenToken;
        this.tokenExpiresOn = value.tokenExpiresOn;
    }

    public AlbumAccessToken(
        Integer   albumId,
        String    albumName,
        String    albumDescription,
        Integer   tokenId,
        String    tokenToken,
        Timestamp tokenExpiresOn
    ) {
        this.albumId = albumId;
        this.albumName = albumName;
        this.albumDescription = albumDescription;
        this.tokenId = tokenId;
        this.tokenToken = tokenToken;
        this.tokenExpiresOn = tokenExpiresOn;
    }

    /**
     * Getter for <code>frickl.album_access_token.album_id</code>. Auto
     * incremented id of this table.
     */
    public Integer getAlbumId() {
        return this.albumId;
    }

    /**
     * Setter for <code>frickl.album_access_token.album_id</code>. Auto
     * incremented id of this table.
     */
    public void setAlbumId(Integer albumId) {
        this.albumId = albumId;
    }

    /**
     * Getter for <code>frickl.album_access_token.album_name</code>. The name of
     * the album. Should ideally be relatively short.
     */
    public String getAlbumName() {
        return this.albumName;
    }

    /**
     * Setter for <code>frickl.album_access_token.album_name</code>. The name of
     * the album. Should ideally be relatively short.
     */
    public void setAlbumName(String albumName) {
        this.albumName = albumName;
    }

    /**
     * Getter for <code>frickl.album_access_token.album_description</code>.
     * Optional description of the album.
     */
    public String getAlbumDescription() {
        return this.albumDescription;
    }

    /**
     * Setter for <code>frickl.album_access_token.album_description</code>.
     * Optional description of the album.
     */
    public void setAlbumDescription(String albumDescription) {
        this.albumDescription = albumDescription;
    }

    /**
     * Getter for <code>frickl.album_access_token.token_id</code>. Auto
     * incremented id of this table.
     */
    public Integer getTokenId() {
        return this.tokenId;
    }

    /**
     * Setter for <code>frickl.album_access_token.token_id</code>. Auto
     * incremented id of this table.
     */
    public void setTokenId(Integer tokenId) {
        this.tokenId = tokenId;
    }

    /**
     * Getter for <code>frickl.album_access_token.token_token</code>. The access
     * token.
     */
    public String getTokenToken() {
        return this.tokenToken;
    }

    /**
     * Setter for <code>frickl.album_access_token.token_token</code>. The access
     * token.
     */
    public void setTokenToken(String tokenToken) {
        this.tokenToken = tokenToken;
    }

    /**
     * Getter for <code>frickl.album_access_token.token_expires_on</code>. When
     * this token expires.
     */
    public Timestamp getTokenExpiresOn() {
        return this.tokenExpiresOn;
    }

    /**
     * Setter for <code>frickl.album_access_token.token_expires_on</code>. When
     * this token expires.
     */
    public void setTokenExpiresOn(Timestamp tokenExpiresOn) {
        this.tokenExpiresOn = tokenExpiresOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AlbumAccessToken (");

        sb.append(albumId);
        sb.append(", ").append(albumName);
        sb.append(", ").append(albumDescription);
        sb.append(", ").append(tokenId);
        sb.append(", ").append(tokenToken);
        sb.append(", ").append(tokenExpiresOn);

        sb.append(")");
        return sb.toString();
    }
}
