/*
 * This file is generated by jOOQ.
 */
package raubach.fricklweb.server.database.tables.pojos;


import java.io.Serializable;

import org.jooq.JSON;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImageTimeline implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer year;
    private Integer month;
    private JSON    ids;

    public ImageTimeline() {}

    public ImageTimeline(ImageTimeline value) {
        this.year = value.year;
        this.month = value.month;
        this.ids = value.ids;
    }

    public ImageTimeline(
        Integer year,
        Integer month,
        JSON    ids
    ) {
        this.year = year;
        this.month = month;
        this.ids = ids;
    }

    /**
     * Getter for <code>frickl.image_timeline.year</code>.
     */
    public Integer getYear() {
        return this.year;
    }

    /**
     * Setter for <code>frickl.image_timeline.year</code>.
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * Getter for <code>frickl.image_timeline.month</code>.
     */
    public Integer getMonth() {
        return this.month;
    }

    /**
     * Setter for <code>frickl.image_timeline.month</code>.
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * Getter for <code>frickl.image_timeline.ids</code>.
     */
    public JSON getIds() {
        return this.ids;
    }

    /**
     * Setter for <code>frickl.image_timeline.ids</code>.
     */
    public void setIds(JSON ids) {
        this.ids = ids;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ImageTimeline (");

        sb.append(year);
        sb.append(", ").append(month);
        sb.append(", ").append(ids);

        sb.append(")");
        return sb.toString();
    }
}
