/*
 * This file is generated by jOOQ.
 */
package raubach.fricklweb.server.database.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LatLngs implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer    id;
    private String     path;
    private Integer    albumId;
    private Byte       isPublic;
    private BigDecimal latitude;
    private BigDecimal longitude;

    public LatLngs() {}

    public LatLngs(LatLngs value) {
        this.id = value.id;
        this.path = value.path;
        this.albumId = value.albumId;
        this.isPublic = value.isPublic;
        this.latitude = value.latitude;
        this.longitude = value.longitude;
    }

    public LatLngs(
        Integer    id,
        String     path,
        Integer    albumId,
        Byte       isPublic,
        BigDecimal latitude,
        BigDecimal longitude
    ) {
        this.id = id;
        this.path = path;
        this.albumId = albumId;
        this.isPublic = isPublic;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    /**
     * Getter for <code>frickl.lat_lngs.id</code>. Auto incremented id of this
     * table.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>frickl.lat_lngs.id</code>. Auto incremented id of this
     * table.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>frickl.lat_lngs.path</code>. The path to the image
     * relative to the base path of the setup.
     */
    public String getPath() {
        return this.path;
    }

    /**
     * Setter for <code>frickl.lat_lngs.path</code>. The path to the image
     * relative to the base path of the setup.
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * Getter for <code>frickl.lat_lngs.album_id</code>. The album this image
     * belongs to. This will be the containing folder.
     */
    public Integer getAlbumId() {
        return this.albumId;
    }

    /**
     * Setter for <code>frickl.lat_lngs.album_id</code>. The album this image
     * belongs to. This will be the containing folder.
     */
    public void setAlbumId(Integer albumId) {
        this.albumId = albumId;
    }

    /**
     * Getter for <code>frickl.lat_lngs.is_public</code>.
     */
    public Byte getIsPublic() {
        return this.isPublic;
    }

    /**
     * Setter for <code>frickl.lat_lngs.is_public</code>.
     */
    public void setIsPublic(Byte isPublic) {
        this.isPublic = isPublic;
    }

    /**
     * Getter for <code>frickl.lat_lngs.latitude</code>.
     */
    public BigDecimal getLatitude() {
        return this.latitude;
    }

    /**
     * Setter for <code>frickl.lat_lngs.latitude</code>.
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * Getter for <code>frickl.lat_lngs.longitude</code>.
     */
    public BigDecimal getLongitude() {
        return this.longitude;
    }

    /**
     * Setter for <code>frickl.lat_lngs.longitude</code>.
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LatLngs (");

        sb.append(id);
        sb.append(", ").append(path);
        sb.append(", ").append(albumId);
        sb.append(", ").append(isPublic);
        sb.append(", ").append(latitude);
        sb.append(", ").append(longitude);

        sb.append(")");
        return sb.toString();
    }
}
