/*
 * This file is generated by jOOQ.
 */
package raubach.fricklweb.server.database.tables.pojos;


import java.io.Serializable;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatsCamera implements Serializable {

    private static final long serialVersionUID = 1L;

    private String camera;
    private Long   count;

    public StatsCamera() {}

    public StatsCamera(StatsCamera value) {
        this.camera = value.camera;
        this.count = value.count;
    }

    public StatsCamera(
        String camera,
        Long   count
    ) {
        this.camera = camera;
        this.count = count;
    }

    /**
     * Getter for <code>frickl.stats_camera.camera</code>.
     */
    public String getCamera() {
        return this.camera;
    }

    /**
     * Setter for <code>frickl.stats_camera.camera</code>.
     */
    public void setCamera(String camera) {
        this.camera = camera;
    }

    /**
     * Getter for <code>frickl.stats_camera.count</code>.
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Setter for <code>frickl.stats_camera.count</code>.
     */
    public void setCount(Long count) {
        this.count = count;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StatsCamera (");

        sb.append(camera);
        sb.append(", ").append(count);

        sb.append(")");
        return sb.toString();
    }
}
