/*
 * This file is generated by jOOQ.
 */
package raubach.frickl.next.codegen.tables.pojos;


import java.io.Serializable;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlbumAccessToken implements Serializable {

    private static final long serialVersionUID = 1L;


    public AlbumAccessToken() {}

    public AlbumAccessToken(AlbumAccessToken value) {
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AlbumAccessToken (");


        sb.append(")");
        return sb.toString();
    }
}
