/*
 * This file is generated by jOOQ.
 */
package raubach.frickl.next.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlbumUsers implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   userId;
    private Integer   albumId;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public AlbumUsers() {}

    public AlbumUsers(AlbumUsers value) {
        this.userId = value.userId;
        this.albumId = value.albumId;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public AlbumUsers(
        Integer   userId,
        Integer   albumId,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.userId = userId;
        this.albumId = albumId;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>frickl.album_users.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>frickl.album_users.user_id</code>.
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>frickl.album_users.album_id</code>.
     */
    public Integer getAlbumId() {
        return this.albumId;
    }

    /**
     * Setter for <code>frickl.album_users.album_id</code>.
     */
    public void setAlbumId(Integer albumId) {
        this.albumId = albumId;
    }

    /**
     * Getter for <code>frickl.album_users.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>frickl.album_users.created_on</code>.
     */
    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * Getter for <code>frickl.album_users.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>frickl.album_users.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AlbumUsers (");

        sb.append(userId);
        sb.append(", ").append(albumId);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
