/*
 * This file is generated by jOOQ.
 */
package raubach.frickl.next.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Date;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CalendarData implements Serializable {

    private static final long serialVersionUID = 1L;

    private Date date;
    private Long count;

    public CalendarData() {}

    public CalendarData(CalendarData value) {
        this.date = value.date;
        this.count = value.count;
    }

    public CalendarData(
        Date date,
        Long count
    ) {
        this.date = date;
        this.count = count;
    }

    /**
     * Getter for <code>frickl.calendar_data.date</code>.
     */
    public Date getDate() {
        return this.date;
    }

    /**
     * Setter for <code>frickl.calendar_data.date</code>.
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * Getter for <code>frickl.calendar_data.count</code>.
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Setter for <code>frickl.calendar_data.count</code>.
     */
    public void setCount(Long count) {
        this.count = count;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CalendarData (");

        sb.append(date);
        sb.append(", ").append(count);

        sb.append(")");
        return sb.toString();
    }
}
