/*
 * This file is generated by jOOQ.
 */
package raubach.frickl.next.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import raubach.frickl.next.codegen.enums.UsersViewType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        username;
    private String        password;
    private Short         permissions;
    private UsersViewType viewType;
    private Timestamp     lastLogin;
    private Timestamp     createdOn;
    private Timestamp     updatedOn;

    public Users() {}

    public Users(Users value) {
        this.id = value.id;
        this.username = value.username;
        this.password = value.password;
        this.permissions = value.permissions;
        this.viewType = value.viewType;
        this.lastLogin = value.lastLogin;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Users(
        Integer       id,
        String        username,
        String        password,
        Short         permissions,
        UsersViewType viewType,
        Timestamp     lastLogin,
        Timestamp     createdOn,
        Timestamp     updatedOn
    ) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.permissions = permissions;
        this.viewType = viewType;
        this.lastLogin = lastLogin;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>frickl.users.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>frickl.users.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>frickl.users.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>frickl.users.username</code>.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for <code>frickl.users.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>frickl.users.password</code>.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Getter for <code>frickl.users.permissions</code>.
     */
    public Short getPermissions() {
        return this.permissions;
    }

    /**
     * Setter for <code>frickl.users.permissions</code>.
     */
    public void setPermissions(Short permissions) {
        this.permissions = permissions;
    }

    /**
     * Getter for <code>frickl.users.view_type</code>.
     */
    public UsersViewType getViewType() {
        return this.viewType;
    }

    /**
     * Setter for <code>frickl.users.view_type</code>.
     */
    public void setViewType(UsersViewType viewType) {
        this.viewType = viewType;
    }

    /**
     * Getter for <code>frickl.users.last_login</code>.
     */
    public Timestamp getLastLogin() {
        return this.lastLogin;
    }

    /**
     * Setter for <code>frickl.users.last_login</code>.
     */
    public void setLastLogin(Timestamp lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * Getter for <code>frickl.users.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>frickl.users.created_on</code>.
     */
    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * Getter for <code>frickl.users.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>frickl.users.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(permissions);
        sb.append(", ").append(viewType);
        sb.append(", ").append(lastLogin);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
