/*
 * This file is generated by jOOQ.
 */
package raubach.fricklweb.server.database.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Date;


/**
 * VIEW
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.11.9"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class CalendarData implements Serializable
{

	private static final long serialVersionUID = -795481511;

	private Date date;
	private Long count;

	public CalendarData()
	{
	}

	public CalendarData(CalendarData value)
	{
		this.date = value.date;
		this.count = value.count;
	}

	public CalendarData(
			Date date,
			Long count
	)
	{
		this.date = date;
		this.count = count;
	}

	public Date getDate()
	{
		return this.date;
	}

	public void setDate(Date date)
	{
		this.date = date;
	}

	public Long getCount()
	{
		return this.count;
	}

	public void setCount(Long count)
	{
		this.count = count;
	}

	@Override
	public String toString()
	{
		StringBuilder sb = new StringBuilder("CalendarData (");

		sb.append(date);
		sb.append(", ").append(count);

		sb.append(")");
		return sb.toString();
	}
}
