/*
 * This file is generated by jOOQ.
 */
package raubach.fricklweb.server.database;


import javax.annotation.*;

import raubach.fricklweb.server.database.tables.*;


/**
 * Convenience access to all tables in frickl
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.11.9"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables
{

	/**
	 * The table <code>frickl.albums</code>.
	 */
	public static final Albums ALBUMS = raubach.fricklweb.server.database.tables.Albums.ALBUMS;

	/**
	 * VIEW
	 */
	public static final CalendarData CALENDAR_DATA = raubach.fricklweb.server.database.tables.CalendarData.CALENDAR_DATA;

	/**
	 * The table <code>frickl.images</code>.
	 */
	public static final Images IMAGES = raubach.fricklweb.server.database.tables.Images.IMAGES;

	/**
	 * The table <code>frickl.image_tags</code>.
	 */
	public static final ImageTags IMAGE_TAGS = raubach.fricklweb.server.database.tables.ImageTags.IMAGE_TAGS;

	/**
	 * VIEW
	 */
	public static final LatLngs LAT_LNGS = raubach.fricklweb.server.database.tables.LatLngs.LAT_LNGS;

	/**
	 * VIEW
	 */
	public static final StatsCamera STATS_CAMERA = raubach.fricklweb.server.database.tables.StatsCamera.STATS_CAMERA;

	/**
	 * The table <code>frickl.tags</code>.
	 */
	public static final Tags TAGS = raubach.fricklweb.server.database.tables.Tags.TAGS;
}
