/*
 * This file is generated by jOOQ.
 */
package raubach.fricklweb.server.database;


import javax.annotation.Generated;

import raubach.fricklweb.server.database.tables.AccessTokens;
import raubach.fricklweb.server.database.tables.AlbumStats;
import raubach.fricklweb.server.database.tables.AlbumTokens;
import raubach.fricklweb.server.database.tables.Albums;
import raubach.fricklweb.server.database.tables.CalendarData;
import raubach.fricklweb.server.database.tables.ImageTags;
import raubach.fricklweb.server.database.tables.ImageTimeline;
import raubach.fricklweb.server.database.tables.Images;
import raubach.fricklweb.server.database.tables.LatLngs;
import raubach.fricklweb.server.database.tables.SchemaVersion;
import raubach.fricklweb.server.database.tables.StatsCamera;
import raubach.fricklweb.server.database.tables.Tags;


/**
 * Convenience access to all tables in frickl
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * This table contains all tags that can be used to access folders that aren't public.
     */
    public static final AccessTokens ACCESS_TOKENS = raubach.fricklweb.server.database.tables.AccessTokens.ACCESS_TOKENS;

    /**
     * VIEW
     */
    public static final AlbumStats ALBUM_STATS = raubach.fricklweb.server.database.tables.AlbumStats.ALBUM_STATS;

    /**
     * This table contains the mapping between access tokens and albums.
     */
    public static final AlbumTokens ALBUM_TOKENS = raubach.fricklweb.server.database.tables.AlbumTokens.ALBUM_TOKENS;

    /**
     * This table contains all albums in Frickl. Albums correspond to image folders on the file system.
     */
    public static final Albums ALBUMS = raubach.fricklweb.server.database.tables.Albums.ALBUMS;

    /**
     * VIEW
     */
    public static final CalendarData CALENDAR_DATA = raubach.fricklweb.server.database.tables.CalendarData.CALENDAR_DATA;

    /**
     * This table joins `images` and `tags` and therefore defines which tags an image is tagged with.
     */
    public static final ImageTags IMAGE_TAGS = raubach.fricklweb.server.database.tables.ImageTags.IMAGE_TAGS;

    /**
     * VIEW
     */
    public static final ImageTimeline IMAGE_TIMELINE = raubach.fricklweb.server.database.tables.ImageTimeline.IMAGE_TIMELINE;

    /**
     * This table contains images from the file system.
     */
    public static final Images IMAGES = raubach.fricklweb.server.database.tables.Images.IMAGES;

    /**
     * VIEW
     */
    public static final LatLngs LAT_LNGS = raubach.fricklweb.server.database.tables.LatLngs.LAT_LNGS;

    /**
     * The table <code>frickl.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = raubach.fricklweb.server.database.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * VIEW
     */
    public static final StatsCamera STATS_CAMERA = raubach.fricklweb.server.database.tables.StatsCamera.STATS_CAMERA;

    /**
     * This table contains all tags/keywords that have been defined and assigned to images.
     */
    public static final Tags TAGS = raubach.fricklweb.server.database.tables.Tags.TAGS;
}
