/*
 * This file is generated by jOOQ.
 */
package raubach.frickl.next.codegen.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum UsersViewType implements EnumType {

    VIEW_ALL("VIEW_ALL"),

    ALBUM_PERMISSION("ALBUM_PERMISSION");

    private final String literal;

    private UsersViewType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "users_view_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static UsersViewType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(UsersViewType.class, literal);
    }
}
