/*
 * This file is generated by jOOQ.
 */
package raubach.fricklweb.server.database.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import raubach.fricklweb.server.database.tables.AccessTokens;


/**
 * This table contains all tokens that can be used to access folders that 
 * aren't public.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccessTokensRecord extends UpdatableRecordImpl<AccessTokensRecord> implements Record5<Integer, String, Timestamp, Timestamp, Timestamp> {

    private static final long serialVersionUID = -930561075;

    /**
     * Setter for <code>frickl.access_tokens.id</code>. Auto incremented id of this table.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>frickl.access_tokens.id</code>. Auto incremented id of this table.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>frickl.access_tokens.token</code>. The access token.
     */
    public void setToken(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>frickl.access_tokens.token</code>. The access token.
     */
    public String getToken() {
        return (String) get(1);
    }

    /**
     * Setter for <code>frickl.access_tokens.expires_on</code>. When this token expires.
     */
    public void setExpiresOn(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>frickl.access_tokens.expires_on</code>. When this token expires.
     */
    public Timestamp getExpiresOn() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>frickl.access_tokens.created_on</code>. When this record has been created.
     */
    public void setCreatedOn(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>frickl.access_tokens.created_on</code>. When this record has been created.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>frickl.access_tokens.updated_on</code>. When this record has last been updated.
     */
    public void setUpdatedOn(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>frickl.access_tokens.updated_on</code>. When this record has last been updated.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Timestamp, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Timestamp, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return AccessTokens.ACCESS_TOKENS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AccessTokens.ACCESS_TOKENS.TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return AccessTokens.ACCESS_TOKENS.EXPIRES_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return AccessTokens.ACCESS_TOKENS.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return AccessTokens.ACCESS_TOKENS.UPDATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getExpiresOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getExpiresOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccessTokensRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccessTokensRecord value2(String value) {
        setToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccessTokensRecord value3(Timestamp value) {
        setExpiresOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccessTokensRecord value4(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccessTokensRecord value5(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccessTokensRecord values(Integer value1, String value2, Timestamp value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccessTokensRecord
     */
    public AccessTokensRecord() {
        super(AccessTokens.ACCESS_TOKENS);
    }

    /**
     * Create a detached, initialised AccessTokensRecord
     */
    public AccessTokensRecord(Integer id, String token, Timestamp expiresOn, Timestamp createdOn, Timestamp updatedOn) {
        super(AccessTokens.ACCESS_TOKENS);

        set(0, id);
        set(1, token);
        set(2, expiresOn);
        set(3, createdOn);
        set(4, updatedOn);
    }
}
