/*
 * This file is generated by jOOQ.
 */
package raubach.fricklweb.server.database.tables.records;


import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;

import raubach.fricklweb.server.database.tables.ImageTimeline;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImageTimelineRecord extends TableRecordImpl<ImageTimelineRecord> implements Record3<Integer, Integer, JSON> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>frickl.image_timeline.year</code>.
     */
    public void setYear(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>frickl.image_timeline.year</code>.
     */
    public Integer getYear() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>frickl.image_timeline.month</code>.
     */
    public void setMonth(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>frickl.image_timeline.month</code>.
     */
    public Integer getMonth() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>frickl.image_timeline.ids</code>.
     */
    public void setIds(JSON value) {
        set(2, value);
    }

    /**
     * Getter for <code>frickl.image_timeline.ids</code>.
     */
    public JSON getIds() {
        return (JSON) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, JSON> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, JSON> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ImageTimeline.IMAGE_TIMELINE.YEAR;
    }

    @Override
    public Field<Integer> field2() {
        return ImageTimeline.IMAGE_TIMELINE.MONTH;
    }

    @Override
    public Field<JSON> field3() {
        return ImageTimeline.IMAGE_TIMELINE.IDS;
    }

    @Override
    public Integer component1() {
        return getYear();
    }

    @Override
    public Integer component2() {
        return getMonth();
    }

    @Override
    public JSON component3() {
        return getIds();
    }

    @Override
    public Integer value1() {
        return getYear();
    }

    @Override
    public Integer value2() {
        return getMonth();
    }

    @Override
    public JSON value3() {
        return getIds();
    }

    @Override
    public ImageTimelineRecord value1(Integer value) {
        setYear(value);
        return this;
    }

    @Override
    public ImageTimelineRecord value2(Integer value) {
        setMonth(value);
        return this;
    }

    @Override
    public ImageTimelineRecord value3(JSON value) {
        setIds(value);
        return this;
    }

    @Override
    public ImageTimelineRecord values(Integer value1, Integer value2, JSON value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ImageTimelineRecord
     */
    public ImageTimelineRecord() {
        super(ImageTimeline.IMAGE_TIMELINE);
    }

    /**
     * Create a detached, initialised ImageTimelineRecord
     */
    public ImageTimelineRecord(Integer year, Integer month, JSON ids) {
        super(ImageTimeline.IMAGE_TIMELINE);

        setYear(year);
        setMonth(month);
        setIds(ids);
    }

    /**
     * Create a detached, initialised ImageTimelineRecord
     */
    public ImageTimelineRecord(raubach.fricklweb.server.database.tables.pojos.ImageTimeline value) {
        super(ImageTimeline.IMAGE_TIMELINE);

        if (value != null) {
            setYear(value.getYear());
            setMonth(value.getMonth());
            setIds(value.getIds());
        }
    }
}
