/*
 * This file is generated by jOOQ.
 */
package raubach.frickl.next.codegen;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import raubach.frickl.next.codegen.tables.AlbumCounts;
import raubach.frickl.next.codegen.tables.AlbumUsers;
import raubach.frickl.next.codegen.tables.Albums;
import raubach.frickl.next.codegen.tables.ImageTags;
import raubach.frickl.next.codegen.tables.Images;
import raubach.frickl.next.codegen.tables.SchemaVersion;
import raubach.frickl.next.codegen.tables.Tags;
import raubach.frickl.next.codegen.tables.Users;
import raubach.frickl.next.codegen.tables.records.AlbumCountsRecord;
import raubach.frickl.next.codegen.tables.records.AlbumUsersRecord;
import raubach.frickl.next.codegen.tables.records.AlbumsRecord;
import raubach.frickl.next.codegen.tables.records.ImageTagsRecord;
import raubach.frickl.next.codegen.tables.records.ImagesRecord;
import raubach.frickl.next.codegen.tables.records.SchemaVersionRecord;
import raubach.frickl.next.codegen.tables.records.TagsRecord;
import raubach.frickl.next.codegen.tables.records.UsersRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * frickl.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AlbumCountsRecord> KEY_ALBUM_COUNTS_PRIMARY = Internal.createUniqueKey(AlbumCounts.ALBUM_COUNTS, DSL.name("KEY_album_counts_PRIMARY"), new TableField[] { AlbumCounts.ALBUM_COUNTS.ALBUM_ID }, true);
    public static final UniqueKey<AlbumUsersRecord> KEY_ALBUM_USERS_PRIMARY = Internal.createUniqueKey(AlbumUsers.ALBUM_USERS, DSL.name("KEY_album_users_PRIMARY"), new TableField[] { AlbumUsers.ALBUM_USERS.USER_ID, AlbumUsers.ALBUM_USERS.ALBUM_ID }, true);
    public static final UniqueKey<AlbumsRecord> KEY_ALBUMS_PRIMARY = Internal.createUniqueKey(Albums.ALBUMS, DSL.name("KEY_albums_PRIMARY"), new TableField[] { Albums.ALBUMS.ID }, true);
    public static final UniqueKey<ImageTagsRecord> KEY_IMAGE_TAGS_PRIMARY = Internal.createUniqueKey(ImageTags.IMAGE_TAGS, DSL.name("KEY_image_tags_PRIMARY"), new TableField[] { ImageTags.IMAGE_TAGS.IMAGE_ID, ImageTags.IMAGE_TAGS.TAG_ID }, true);
    public static final UniqueKey<ImagesRecord> KEY_IMAGES_PRIMARY = Internal.createUniqueKey(Images.IMAGES, DSL.name("KEY_images_PRIMARY"), new TableField[] { Images.IMAGES.ID }, true);
    public static final UniqueKey<SchemaVersionRecord> KEY_SCHEMA_VERSION_PRIMARY = Internal.createUniqueKey(SchemaVersion.SCHEMA_VERSION, DSL.name("KEY_schema_version_PRIMARY"), new TableField[] { SchemaVersion.SCHEMA_VERSION.INSTALLED_RANK }, true);
    public static final UniqueKey<TagsRecord> KEY_TAGS_PRIMARY = Internal.createUniqueKey(Tags.TAGS, DSL.name("KEY_tags_PRIMARY"), new TableField[] { Tags.TAGS.ID }, true);
    public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = Internal.createUniqueKey(Users.USERS, DSL.name("KEY_users_PRIMARY"), new TableField[] { Users.USERS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AlbumCountsRecord, AlbumsRecord> ALBUM_COUNTS_IBFK_1 = Internal.createForeignKey(AlbumCounts.ALBUM_COUNTS, DSL.name("album_counts_ibfk_1"), new TableField[] { AlbumCounts.ALBUM_COUNTS.ALBUM_ID }, Keys.KEY_ALBUMS_PRIMARY, new TableField[] { Albums.ALBUMS.ID }, true);
    public static final ForeignKey<AlbumUsersRecord, UsersRecord> ALBUM_USERS_IBFK_1 = Internal.createForeignKey(AlbumUsers.ALBUM_USERS, DSL.name("album_users_ibfk_1"), new TableField[] { AlbumUsers.ALBUM_USERS.USER_ID }, Keys.KEY_USERS_PRIMARY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<AlbumUsersRecord, AlbumsRecord> ALBUM_USERS_IBFK_2 = Internal.createForeignKey(AlbumUsers.ALBUM_USERS, DSL.name("album_users_ibfk_2"), new TableField[] { AlbumUsers.ALBUM_USERS.ALBUM_ID }, Keys.KEY_ALBUMS_PRIMARY, new TableField[] { Albums.ALBUMS.ID }, true);
    public static final ForeignKey<AlbumsRecord, ImagesRecord> ALBUMS_IBFK_1 = Internal.createForeignKey(Albums.ALBUMS, DSL.name("albums_ibfk_1"), new TableField[] { Albums.ALBUMS.BANNER_IMAGE_ID }, Keys.KEY_IMAGES_PRIMARY, new TableField[] { Images.IMAGES.ID }, true);
    public static final ForeignKey<AlbumsRecord, AlbumsRecord> ALBUMS_IBFK_2 = Internal.createForeignKey(Albums.ALBUMS, DSL.name("albums_ibfk_2"), new TableField[] { Albums.ALBUMS.PARENT_ALBUM_ID }, Keys.KEY_ALBUMS_PRIMARY, new TableField[] { Albums.ALBUMS.ID }, true);
    public static final ForeignKey<AlbumsRecord, UsersRecord> ALBUMS_IBFK_3 = Internal.createForeignKey(Albums.ALBUMS, DSL.name("albums_ibfk_3"), new TableField[] { Albums.ALBUMS.CREATED_BY }, Keys.KEY_USERS_PRIMARY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<ImageTagsRecord, ImagesRecord> IMAGE_TAGS_IBFK_1 = Internal.createForeignKey(ImageTags.IMAGE_TAGS, DSL.name("image_tags_ibfk_1"), new TableField[] { ImageTags.IMAGE_TAGS.IMAGE_ID }, Keys.KEY_IMAGES_PRIMARY, new TableField[] { Images.IMAGES.ID }, true);
    public static final ForeignKey<ImageTagsRecord, TagsRecord> IMAGE_TAGS_IBFK_2 = Internal.createForeignKey(ImageTags.IMAGE_TAGS, DSL.name("image_tags_ibfk_2"), new TableField[] { ImageTags.IMAGE_TAGS.TAG_ID }, Keys.KEY_TAGS_PRIMARY, new TableField[] { Tags.TAGS.ID }, true);
    public static final ForeignKey<ImagesRecord, AlbumsRecord> IMAGES_IBFK_1 = Internal.createForeignKey(Images.IMAGES, DSL.name("images_ibfk_1"), new TableField[] { Images.IMAGES.ALBUM_ID }, Keys.KEY_ALBUMS_PRIMARY, new TableField[] { Albums.ALBUMS.ID }, true);
    public static final ForeignKey<ImagesRecord, UsersRecord> IMAGES_IBFK_2 = Internal.createForeignKey(Images.IMAGES, DSL.name("images_ibfk_2"), new TableField[] { Images.IMAGES.CREATED_BY }, Keys.KEY_USERS_PRIMARY, new TableField[] { Users.USERS.ID }, true);
}
