/*
 * This file is generated by jOOQ.
 */
package raubach.frickl.next.codegen.tables.records;


import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;

import raubach.frickl.next.codegen.enums.ImagesDataType;
import raubach.frickl.next.codegen.tables.Images;
import raubach.frickl.next.pojo.Exif;


/**
 * This table contains images from the file system.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImagesRecord extends UpdatableRecordImpl<ImagesRecord> implements Record12<Integer, String, String, Byte, Exif, Integer, Byte, Integer, ImagesDataType, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>frickl.images.id</code>. Auto incremented id of this
     * table.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>frickl.images.id</code>. Auto incremented id of this
     * table.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>frickl.images.path</code>. The path to the image
     * relative to the base path of the setup.
     */
    public void setPath(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>frickl.images.path</code>. The path to the image
     * relative to the base path of the setup.
     */
    public String getPath() {
        return (String) get(1);
    }

    /**
     * Setter for <code>frickl.images.name</code>. The name of the image. This
     * will be the filename.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>frickl.images.name</code>. The name of the image. This
     * will be the filename.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>frickl.images.is_favorite</code>. Boolean deciding if
     * this image is one of the favorites.
     */
    public void setIsFavorite(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>frickl.images.is_favorite</code>. Boolean deciding if
     * this image is one of the favorites.
     */
    public Byte getIsFavorite() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>frickl.images.exif</code>. Optional Exif information in
     * JSON format.
     */
    public void setExif(Exif value) {
        set(4, value);
    }

    /**
     * Getter for <code>frickl.images.exif</code>. Optional Exif information in
     * JSON format.
     */
    public Exif getExif() {
        return (Exif) get(4);
    }

    /**
     * Setter for <code>frickl.images.album_id</code>. The album this image
     * belongs to. This will be the containing folder.
     */
    public void setAlbumId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>frickl.images.album_id</code>. The album this image
     * belongs to. This will be the containing folder.
     */
    public Integer getAlbumId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>frickl.images.is_public</code>.
     */
    public void setIsPublic(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>frickl.images.is_public</code>.
     */
    public Byte getIsPublic() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>frickl.images.view_count</code>.
     */
    public void setViewCount(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>frickl.images.view_count</code>.
     */
    public Integer getViewCount() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>frickl.images.data_type</code>.
     */
    public void setDataType(ImagesDataType value) {
        set(8, value);
    }

    /**
     * Getter for <code>frickl.images.data_type</code>.
     */
    public ImagesDataType getDataType() {
        return (ImagesDataType) get(8);
    }

    /**
     * Setter for <code>frickl.images.created_by</code>. Optional user id.
     * Indicates which user created/uploaded this image.
     */
    public void setCreatedBy(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>frickl.images.created_by</code>. Optional user id.
     * Indicates which user created/uploaded this image.
     */
    public Integer getCreatedBy() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>frickl.images.created_on</code>. When this record has
     * been created.
     */
    public void setCreatedOn(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>frickl.images.created_on</code>. When this record has
     * been created.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>frickl.images.updated_on</code>. When this record has
     * last been updated.
     */
    public void setUpdatedOn(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>frickl.images.updated_on</code>. When this record has
     * last been updated.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Integer, String, String, Byte, Exif, Integer, Byte, Integer, ImagesDataType, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Integer, String, String, Byte, Exif, Integer, Byte, Integer, ImagesDataType, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Images.IMAGES.ID;
    }

    @Override
    public Field<String> field2() {
        return Images.IMAGES.PATH;
    }

    @Override
    public Field<String> field3() {
        return Images.IMAGES.NAME;
    }

    @Override
    public Field<Byte> field4() {
        return Images.IMAGES.IS_FAVORITE;
    }

    @Override
    public Field<Exif> field5() {
        return Images.IMAGES.EXIF;
    }

    @Override
    public Field<Integer> field6() {
        return Images.IMAGES.ALBUM_ID;
    }

    @Override
    public Field<Byte> field7() {
        return Images.IMAGES.IS_PUBLIC;
    }

    @Override
    public Field<Integer> field8() {
        return Images.IMAGES.VIEW_COUNT;
    }

    @Override
    public Field<ImagesDataType> field9() {
        return Images.IMAGES.DATA_TYPE;
    }

    @Override
    public Field<Integer> field10() {
        return Images.IMAGES.CREATED_BY;
    }

    @Override
    public Field<Timestamp> field11() {
        return Images.IMAGES.CREATED_ON;
    }

    @Override
    public Field<Timestamp> field12() {
        return Images.IMAGES.UPDATED_ON;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getPath();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Byte component4() {
        return getIsFavorite();
    }

    @Override
    public Exif component5() {
        return getExif();
    }

    @Override
    public Integer component6() {
        return getAlbumId();
    }

    @Override
    public Byte component7() {
        return getIsPublic();
    }

    @Override
    public Integer component8() {
        return getViewCount();
    }

    @Override
    public ImagesDataType component9() {
        return getDataType();
    }

    @Override
    public Integer component10() {
        return getCreatedBy();
    }

    @Override
    public Timestamp component11() {
        return getCreatedOn();
    }

    @Override
    public Timestamp component12() {
        return getUpdatedOn();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getPath();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Byte value4() {
        return getIsFavorite();
    }

    @Override
    public Exif value5() {
        return getExif();
    }

    @Override
    public Integer value6() {
        return getAlbumId();
    }

    @Override
    public Byte value7() {
        return getIsPublic();
    }

    @Override
    public Integer value8() {
        return getViewCount();
    }

    @Override
    public ImagesDataType value9() {
        return getDataType();
    }

    @Override
    public Integer value10() {
        return getCreatedBy();
    }

    @Override
    public Timestamp value11() {
        return getCreatedOn();
    }

    @Override
    public Timestamp value12() {
        return getUpdatedOn();
    }

    @Override
    public ImagesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ImagesRecord value2(String value) {
        setPath(value);
        return this;
    }

    @Override
    public ImagesRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public ImagesRecord value4(Byte value) {
        setIsFavorite(value);
        return this;
    }

    @Override
    public ImagesRecord value5(Exif value) {
        setExif(value);
        return this;
    }

    @Override
    public ImagesRecord value6(Integer value) {
        setAlbumId(value);
        return this;
    }

    @Override
    public ImagesRecord value7(Byte value) {
        setIsPublic(value);
        return this;
    }

    @Override
    public ImagesRecord value8(Integer value) {
        setViewCount(value);
        return this;
    }

    @Override
    public ImagesRecord value9(ImagesDataType value) {
        setDataType(value);
        return this;
    }

    @Override
    public ImagesRecord value10(Integer value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public ImagesRecord value11(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public ImagesRecord value12(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public ImagesRecord values(Integer value1, String value2, String value3, Byte value4, Exif value5, Integer value6, Byte value7, Integer value8, ImagesDataType value9, Integer value10, Timestamp value11, Timestamp value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ImagesRecord
     */
    public ImagesRecord() {
        super(Images.IMAGES);
    }

    /**
     * Create a detached, initialised ImagesRecord
     */
    public ImagesRecord(Integer id, String path, String name, Byte isFavorite, Exif exif, Integer albumId, Byte isPublic, Integer viewCount, ImagesDataType dataType, Integer createdBy, Timestamp createdOn, Timestamp updatedOn) {
        super(Images.IMAGES);

        setId(id);
        setPath(path);
        setName(name);
        setIsFavorite(isFavorite);
        setExif(exif);
        setAlbumId(albumId);
        setIsPublic(isPublic);
        setViewCount(viewCount);
        setDataType(dataType);
        setCreatedBy(createdBy);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
    }

    /**
     * Create a detached, initialised ImagesRecord
     */
    public ImagesRecord(raubach.frickl.next.codegen.tables.pojos.Images value) {
        super(Images.IMAGES);

        if (value != null) {
            setId(value.getId());
            setPath(value.getPath());
            setName(value.getName());
            setIsFavorite(value.getIsFavorite());
            setExif(value.getExif());
            setAlbumId(value.getAlbumId());
            setIsPublic(value.getIsPublic());
            setViewCount(value.getViewCount());
            setDataType(value.getDataType());
            setCreatedBy(value.getCreatedBy());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
        }
    }
}
