/*
 * This file is generated by jOOQ.
 */
package raubach.frickl.next.codegen.tables.records;


import java.math.BigDecimal;
import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.TableRecordImpl;

import raubach.frickl.next.codegen.enums.LatLngsDataType;
import raubach.frickl.next.codegen.tables.LatLngs;
import raubach.frickl.next.pojo.Exif;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LatLngsRecord extends TableRecordImpl<LatLngsRecord> implements Record14<Integer, String, String, Byte, Exif, Integer, Byte, Integer, LatLngsDataType, Integer, Timestamp, Timestamp, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>frickl.lat_lngs.id</code>. Auto incremented id of this
     * table.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>frickl.lat_lngs.id</code>. Auto incremented id of this
     * table.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>frickl.lat_lngs.path</code>. The path to the image
     * relative to the base path of the setup.
     */
    public void setPath(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>frickl.lat_lngs.path</code>. The path to the image
     * relative to the base path of the setup.
     */
    public String getPath() {
        return (String) get(1);
    }

    /**
     * Setter for <code>frickl.lat_lngs.name</code>. The name of the image. This
     * will be the filename.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>frickl.lat_lngs.name</code>. The name of the image. This
     * will be the filename.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>frickl.lat_lngs.is_favorite</code>. Boolean deciding if
     * this image is one of the favorites.
     */
    public void setIsFavorite(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>frickl.lat_lngs.is_favorite</code>. Boolean deciding if
     * this image is one of the favorites.
     */
    public Byte getIsFavorite() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>frickl.lat_lngs.exif</code>. Optional Exif information
     * in JSON format.
     */
    public void setExif(Exif value) {
        set(4, value);
    }

    /**
     * Getter for <code>frickl.lat_lngs.exif</code>. Optional Exif information
     * in JSON format.
     */
    public Exif getExif() {
        return (Exif) get(4);
    }

    /**
     * Setter for <code>frickl.lat_lngs.album_id</code>. The album this image
     * belongs to. This will be the containing folder.
     */
    public void setAlbumId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>frickl.lat_lngs.album_id</code>. The album this image
     * belongs to. This will be the containing folder.
     */
    public Integer getAlbumId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>frickl.lat_lngs.is_public</code>.
     */
    public void setIsPublic(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>frickl.lat_lngs.is_public</code>.
     */
    public Byte getIsPublic() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>frickl.lat_lngs.view_count</code>.
     */
    public void setViewCount(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>frickl.lat_lngs.view_count</code>.
     */
    public Integer getViewCount() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>frickl.lat_lngs.data_type</code>.
     */
    public void setDataType(LatLngsDataType value) {
        set(8, value);
    }

    /**
     * Getter for <code>frickl.lat_lngs.data_type</code>.
     */
    public LatLngsDataType getDataType() {
        return (LatLngsDataType) get(8);
    }

    /**
     * Setter for <code>frickl.lat_lngs.created_by</code>. Optional user id.
     * Indicates which user created/uploaded this image.
     */
    public void setCreatedBy(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>frickl.lat_lngs.created_by</code>. Optional user id.
     * Indicates which user created/uploaded this image.
     */
    public Integer getCreatedBy() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>frickl.lat_lngs.created_on</code>. When this record has
     * been created.
     */
    public void setCreatedOn(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>frickl.lat_lngs.created_on</code>. When this record has
     * been created.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>frickl.lat_lngs.updated_on</code>. When this record has
     * last been updated.
     */
    public void setUpdatedOn(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>frickl.lat_lngs.updated_on</code>. When this record has
     * last been updated.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>frickl.lat_lngs.latitude</code>.
     */
    public void setLatitude(BigDecimal value) {
        set(12, value);
    }

    /**
     * Getter for <code>frickl.lat_lngs.latitude</code>.
     */
    public BigDecimal getLatitude() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>frickl.lat_lngs.longitude</code>.
     */
    public void setLongitude(BigDecimal value) {
        set(13, value);
    }

    /**
     * Getter for <code>frickl.lat_lngs.longitude</code>.
     */
    public BigDecimal getLongitude() {
        return (BigDecimal) get(13);
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Integer, String, String, Byte, Exif, Integer, Byte, Integer, LatLngsDataType, Integer, Timestamp, Timestamp, BigDecimal, BigDecimal> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Integer, String, String, Byte, Exif, Integer, Byte, Integer, LatLngsDataType, Integer, Timestamp, Timestamp, BigDecimal, BigDecimal> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return LatLngs.LAT_LNGS.ID;
    }

    @Override
    public Field<String> field2() {
        return LatLngs.LAT_LNGS.PATH;
    }

    @Override
    public Field<String> field3() {
        return LatLngs.LAT_LNGS.NAME;
    }

    @Override
    public Field<Byte> field4() {
        return LatLngs.LAT_LNGS.IS_FAVORITE;
    }

    @Override
    public Field<Exif> field5() {
        return LatLngs.LAT_LNGS.EXIF;
    }

    @Override
    public Field<Integer> field6() {
        return LatLngs.LAT_LNGS.ALBUM_ID;
    }

    @Override
    public Field<Byte> field7() {
        return LatLngs.LAT_LNGS.IS_PUBLIC;
    }

    @Override
    public Field<Integer> field8() {
        return LatLngs.LAT_LNGS.VIEW_COUNT;
    }

    @Override
    public Field<LatLngsDataType> field9() {
        return LatLngs.LAT_LNGS.DATA_TYPE;
    }

    @Override
    public Field<Integer> field10() {
        return LatLngs.LAT_LNGS.CREATED_BY;
    }

    @Override
    public Field<Timestamp> field11() {
        return LatLngs.LAT_LNGS.CREATED_ON;
    }

    @Override
    public Field<Timestamp> field12() {
        return LatLngs.LAT_LNGS.UPDATED_ON;
    }

    @Override
    public Field<BigDecimal> field13() {
        return LatLngs.LAT_LNGS.LATITUDE;
    }

    @Override
    public Field<BigDecimal> field14() {
        return LatLngs.LAT_LNGS.LONGITUDE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getPath();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Byte component4() {
        return getIsFavorite();
    }

    @Override
    public Exif component5() {
        return getExif();
    }

    @Override
    public Integer component6() {
        return getAlbumId();
    }

    @Override
    public Byte component7() {
        return getIsPublic();
    }

    @Override
    public Integer component8() {
        return getViewCount();
    }

    @Override
    public LatLngsDataType component9() {
        return getDataType();
    }

    @Override
    public Integer component10() {
        return getCreatedBy();
    }

    @Override
    public Timestamp component11() {
        return getCreatedOn();
    }

    @Override
    public Timestamp component12() {
        return getUpdatedOn();
    }

    @Override
    public BigDecimal component13() {
        return getLatitude();
    }

    @Override
    public BigDecimal component14() {
        return getLongitude();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getPath();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Byte value4() {
        return getIsFavorite();
    }

    @Override
    public Exif value5() {
        return getExif();
    }

    @Override
    public Integer value6() {
        return getAlbumId();
    }

    @Override
    public Byte value7() {
        return getIsPublic();
    }

    @Override
    public Integer value8() {
        return getViewCount();
    }

    @Override
    public LatLngsDataType value9() {
        return getDataType();
    }

    @Override
    public Integer value10() {
        return getCreatedBy();
    }

    @Override
    public Timestamp value11() {
        return getCreatedOn();
    }

    @Override
    public Timestamp value12() {
        return getUpdatedOn();
    }

    @Override
    public BigDecimal value13() {
        return getLatitude();
    }

    @Override
    public BigDecimal value14() {
        return getLongitude();
    }

    @Override
    public LatLngsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public LatLngsRecord value2(String value) {
        setPath(value);
        return this;
    }

    @Override
    public LatLngsRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public LatLngsRecord value4(Byte value) {
        setIsFavorite(value);
        return this;
    }

    @Override
    public LatLngsRecord value5(Exif value) {
        setExif(value);
        return this;
    }

    @Override
    public LatLngsRecord value6(Integer value) {
        setAlbumId(value);
        return this;
    }

    @Override
    public LatLngsRecord value7(Byte value) {
        setIsPublic(value);
        return this;
    }

    @Override
    public LatLngsRecord value8(Integer value) {
        setViewCount(value);
        return this;
    }

    @Override
    public LatLngsRecord value9(LatLngsDataType value) {
        setDataType(value);
        return this;
    }

    @Override
    public LatLngsRecord value10(Integer value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public LatLngsRecord value11(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public LatLngsRecord value12(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public LatLngsRecord value13(BigDecimal value) {
        setLatitude(value);
        return this;
    }

    @Override
    public LatLngsRecord value14(BigDecimal value) {
        setLongitude(value);
        return this;
    }

    @Override
    public LatLngsRecord values(Integer value1, String value2, String value3, Byte value4, Exif value5, Integer value6, Byte value7, Integer value8, LatLngsDataType value9, Integer value10, Timestamp value11, Timestamp value12, BigDecimal value13, BigDecimal value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LatLngsRecord
     */
    public LatLngsRecord() {
        super(LatLngs.LAT_LNGS);
    }

    /**
     * Create a detached, initialised LatLngsRecord
     */
    public LatLngsRecord(Integer id, String path, String name, Byte isFavorite, Exif exif, Integer albumId, Byte isPublic, Integer viewCount, LatLngsDataType dataType, Integer createdBy, Timestamp createdOn, Timestamp updatedOn, BigDecimal latitude, BigDecimal longitude) {
        super(LatLngs.LAT_LNGS);

        setId(id);
        setPath(path);
        setName(name);
        setIsFavorite(isFavorite);
        setExif(exif);
        setAlbumId(albumId);
        setIsPublic(isPublic);
        setViewCount(viewCount);
        setDataType(dataType);
        setCreatedBy(createdBy);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        setLatitude(latitude);
        setLongitude(longitude);
    }

    /**
     * Create a detached, initialised LatLngsRecord
     */
    public LatLngsRecord(raubach.frickl.next.codegen.tables.pojos.LatLngs value) {
        super(LatLngs.LAT_LNGS);

        if (value != null) {
            setId(value.getId());
            setPath(value.getPath());
            setName(value.getName());
            setIsFavorite(value.getIsFavorite());
            setExif(value.getExif());
            setAlbumId(value.getAlbumId());
            setIsPublic(value.getIsPublic());
            setViewCount(value.getViewCount());
            setDataType(value.getDataType());
            setCreatedBy(value.getCreatedBy());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            setLatitude(value.getLatitude());
            setLongitude(value.getLongitude());
        }
    }
}
